In [1]:
# Importing naumpy and pandas libraries to read the data

# Supress Warnings
import warnings
warnings.filterwarnings('ignore')

# Import the numpy and pandas package
import numpy as np
import pandas as pd

# Read the given CSV file, and view some sample records
df = pd.read_csv("../c3o-experiments-main/kmeans.csv")
df

instance_count machine_type  slots  memory  data_size_MB  features  \
0                 2   m4.2xlarge     16   64000          8000         5   
1                 2   m4.2xlarge     16   64000          8000         5   
2                 2   m4.2xlarge     16   64000          8000         5   
3                 2   m4.2xlarge     16   64000          8000         5   
4                 2   m4.2xlarge     16   64000          8000         5   
..              ...          ...    ...     ...           ...       ...   
895              12    r4.xlarge     48  366000         16000         5   
896              12    r4.xlarge     48  366000         16000         5   
897              12    r4.xlarge     48  366000         16000         5   
898              12    r4.xlarge     48  366000         16000         5   
899              12    r4.xlarge     48  366000         16000         5   

     observations  k  gross_runtime  
0       150000000  3           1126  
1       150000000  3           1127  
2       150000000  3           1151  
3       150000000  3           1156  
4       150000000  3           1216  
..            ... ..            ...  
895     150000000  3            228  
896     150000000  3            230  
897     150000000  3            232  
898     150000000  3            234  
899     150000000  3            236  

[900 rows x 9 columns]

In [2]:
df = df.drop(["machine_type" ], axis=1)

dataset = df.values



In [3]:
X = dataset[:,0:7]

Y = dataset[:,-1]

print(X,Y)



[[        2        16     64000 ...         5 150000000         3]
 [        2        16     64000 ...         5 150000000         3]
 [        2        16     64000 ...         5 150000000         3]
 ...
 [       12        48    366000 ...         5 150000000         3]
 [       12        48    366000 ...         5 150000000         3]
 [       12        48    366000 ...         5 150000000         3]] [1126 1127 1151 1156 1216  608  608  610  610  614  770  774  774  778
  782 1246 1246 2902 3008 3152 1186 1196 2680 2864 2970  788  794  798
  800  804  958  960  964  972  974 1160 1170 2780 2794 2794 1112 1132
 2710 2714 2718  920  930  930  934  934 1136 1138 1140 1142 1146  844
  856  857 1162 1166  806  806 1124 1126 1130 1724 1750 1752 1760 1780
 2676 2686 2689 4390 4520  848  850  860 4204 4556  806  808  816 4126
 4274 1042 1044 1046 1050 1052 1078 1082 1086 1086 1098 1046 1068 1246
 1260 1264  998 1008 1188 1198 1206 3116 3118 3234 3240 3284 2818 2868
 4298 4310 4490 2900 298

In [4]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)
X_scale


array([[0.        , 0.09090909, 0.00447094, ..., 0.        , 0.5       ,
        0.        ],
       [0.        , 0.09090909, 0.00447094, ..., 0.        , 0.5       ,
        0.        ],
       [0.        , 0.09090909, 0.00447094, ..., 0.        , 0.5       ,
        0.        ],
       ...,
       [1.        , 0.45454545, 0.45454545, ..., 0.        , 0.5       ,
        0.        ],
       [1.        , 0.45454545, 0.45454545, ..., 0.        , 0.5       ,
        0.        ],
       [1.        , 0.45454545, 0.45454545, ..., 0.        , 0.5       ,
        0.        ]])

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_scale, Y, test_size=0.3)

In [21]:
from keras.models import Sequential
from keras.layers import Dense, LSTM

In [27]:
model = Sequential([
    Dense(32, activation='relu', input_shape=(7,)),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid'),
])

In [32]:
model.compile(optimizer='Adam',
              loss='mae',
              metrics=['sparse_categorical_crossentropy '])

In [33]:
hist = model.fit(X_train, Y_train,
          batch_size=32, epochs=100)

Epoch 1/100


ValueError: in user code:

    File "c:\Users\serap\anaconda3\envs\CBeIntelli_3_8\lib\site-packages\keras\engine\training.py", line 1284, in train_function  *
        return step_function(self, iterator)
    File "c:\Users\serap\anaconda3\envs\CBeIntelli_3_8\lib\site-packages\keras\engine\training.py", line 1268, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\serap\anaconda3\envs\CBeIntelli_3_8\lib\site-packages\keras\engine\training.py", line 1249, in run_step  **
        outputs = model.train_step(data)
    File "c:\Users\serap\anaconda3\envs\CBeIntelli_3_8\lib\site-packages\keras\engine\training.py", line 1055, in train_step
        return self.compute_metrics(x, y, y_pred, sample_weight)
    File "c:\Users\serap\anaconda3\envs\CBeIntelli_3_8\lib\site-packages\keras\engine\training.py", line 1149, in compute_metrics
        self.compiled_metrics.update_state(y, y_pred, sample_weight)
    File "c:\Users\serap\anaconda3\envs\CBeIntelli_3_8\lib\site-packages\keras\engine\compile_utils.py", line 577, in update_state
        self.build(y_pred, y_true)
    File "c:\Users\serap\anaconda3\envs\CBeIntelli_3_8\lib\site-packages\keras\engine\compile_utils.py", line 483, in build
        self._metrics = tf.__internal__.nest.map_structure_up_to(
    File "c:\Users\serap\anaconda3\envs\CBeIntelli_3_8\lib\site-packages\keras\engine\compile_utils.py", line 631, in _get_metric_objects
        return [self._get_metric_object(m, y_t, y_p) for m in metrics]
    File "c:\Users\serap\anaconda3\envs\CBeIntelli_3_8\lib\site-packages\keras\engine\compile_utils.py", line 631, in <listcomp>
        return [self._get_metric_object(m, y_t, y_p) for m in metrics]
    File "c:\Users\serap\anaconda3\envs\CBeIntelli_3_8\lib\site-packages\keras\engine\compile_utils.py", line 650, in _get_metric_object
        metric_obj = metrics_mod.get(metric)
    File "c:\Users\serap\anaconda3\envs\CBeIntelli_3_8\lib\site-packages\keras\metrics\__init__.py", line 204, in get
        return deserialize(str(identifier))
    File "c:\Users\serap\anaconda3\envs\CBeIntelli_3_8\lib\site-packages\keras\metrics\__init__.py", line 158, in deserialize
        return deserialize_keras_object(
    File "c:\Users\serap\anaconda3\envs\CBeIntelli_3_8\lib\site-packages\keras\saving\legacy\serialization.py", line 543, in deserialize_keras_object
        raise ValueError(

    ValueError: Unknown metric function: 'sparse_categorical_crossentropy '. Please ensure you are using a `keras.utils.custom_object_scope` and that this object is included in the scope. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.


In [26]:
print(model.predict(X_test), Y_test)

9/9 [==============================] - 1s 5ms/step
[[1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [0.9999947 ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [0.999979  ]
 [0.9999675 ]
 [0.9999999 ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [0.9999995 ]
 [0.99998826]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [0.99998635]
 [0.9999995 ]
 [1.        ]
 [1.        ]
 [0.999979  ]
 [1.        ]
 [1.        ]
 [0.9999998 ]
 [1.        ]
 [1.        ]
 [0.9999996 ]
 [1.        ]
 [1.       